function [output_array, output_table] = extractFeat_v2(filename)
%EXTRACT FEATURES VERSION 2 WITH MMG INCLUDED
%   Driver function to extract features from a given
%   muscle 
%   t_signal = signal table containing all samples of contraction
%   EMG, MMGx, MMGy, MMGz extracted from the signal
%   time indices of muscle contraction extracted by helper function
%   findSingleContraction()

%%%GET PREPROCESSED BIOSIGNALS
t_signal = readtable(filename, 'VariableNamingRule','preserve');
sig = table2array(t_signal);
sig_EMG = sig(:,1);
sig_MMGx = sig(:,4);
sig_MMGy = sig(:,5);
sig_MMGz = sig(:,6);

%[array, tab] = isolateContractions(t_signal, "");
[array, ~] = findSingleContraction(filename, "");
mysize = length(array(:,1));
fprintf("My number of contractions per trial is %d.\n", mysize)
num_feat = 162;
features=zeros(mysize, num_feat);
try
    for i=1:mysize
        %%extract time indices from contractions array
        t_start = array(i, 2);
        t_end = array(i, 3);    
        samp_start = t_start*5000;
        samp_end = t_end*5000;
        t_EMG = sig_EMG(samp_start:samp_end);
        t_MMGx = sig_MMGx(samp_start:samp_end);
        t_MMGy = sig_MMGy(samp_start:samp_end);
        t_MMGz = sig_MMGz(samp_start:samp_end);
        %%fill feature array with extracted features
        features(i, :) = [i,t_start, t_end, ...
        Time_length(t_start, t_end), ...
        Time_mean(t_EMG, t_start, t_end), ...
        Time_median(t_EMG, t_start, t_end), ...
        Time_max(t_EMG, t_start, t_end), ...
        Time_min(t_EMG, t_start, t_end), ...
        Time_std_dev(t_EMG, t_start, t_end), ...
        Time_std_error(t_EMG, t_start, t_end), ...
        Time_var(t_EMG, t_start, t_end), ...
        Time_RMS(t_EMG, t_start, t_end), ...
        Time_meanAbsVal(t_EMG, t_start, t_end), ...
        Time_normalizedMean(t_EMG, t_start, t_end), ...
        Time_normalizedRMS(t_EMG, t_start, t_end), ...
        Time_normalizedStDev(t_EMG, t_start, t_end), ...
        Time_ssi(t_EMG, t_start, t_end), ...
        Time_ZCR(t_EMG, t_start, t_end), ...
        Time_MCR(t_EMG, t_start, t_end), ...
        Time_AOC(t_EMG, t_start, t_end), ...
        Time_skewness(t_EMG, t_start, t_end), ...
        Time_kurtosis(t_EMG, t_start, t_end), ...
        Time_mean_gradient(t_EMG, t_start, t_end), ...
        Time_SNR(t_EMG, t_start, t_end), ...
        Time_mean_xcorr(t_EMG, t_start, t_end), ...
        Time_std_xcorr(t_EMG, t_start, t_end), ...
        Time_sum_xcorr(t_EMG, t_start, t_end), ...
        Freq_mean(t_EMG, t_start, t_end), ...
        Freq_median(t_EMG, t_start, t_end), ...
        Freq_max(t_EMG, t_start, t_end), ...
        Freq_min(t_EMG, t_start, t_end), ...
        Freq_std(t_EMG, t_start, t_end), ...
        Freq_std_error(t_EMG, t_start, t_end), ...
        Freq_var(t_EMG, t_start, t_end), ...
        Freq_peakfreq(t_EMG, t_start, t_end), ...
        Freq_avg_power(t_EMG, t_start, t_end), ...
        Freq_totalpower(t_EMG, t_start, t_end), ...
        Freq_skewness(t_EMG, t_start, t_end), ...
        Freq_kurtosis(t_EMG, t_start, t_end), ...
        Freq_mean_psd(t_EMG, t_start, t_end), ...
        Freq_median_psd(t_EMG, t_start, t_end), ...
        Freq_std_error_psd(t_EMG, t_start, t_end), ...
        corr(t_EMG, t_MMGx), ...
        corr(t_EMG, t_MMGy), ...
        corr(t_EMG, t_MMGz), ...
        corr(t_MMGx, t_MMGy), ...
        corr(t_MMGy, t_MMGz), ...
        corr(t_MMGx, t_MMGz), ...
        Time_mean(t_MMGx, t_start, t_end), ...
        Time_median(t_MMGx, t_start, t_end), ...
        Time_max(t_MMGx, t_start, t_end), ...
        Time_min(t_MMGx, t_start, t_end), ...
        Time_std_dev(t_MMGx, t_start, t_end), ...
        Time_std_error(t_MMGx, t_start, t_end), ...
        Time_var(t_MMGx, t_start, t_end), ...
        Time_RMS(t_MMGx, t_start, t_end), ...
        Time_meanAbsVal(t_MMGx, t_start, t_end), ...
        Time_normalizedMean(t_MMGx, t_start, t_end), ...
        Time_normalizedRMS(t_MMGx, t_start, t_end), ...
        Time_normalizedStDev(t_MMGx, t_start, t_end), ...
        Time_ssi(t_MMGx, t_start, t_end), ...
        Time_ZCR(t_MMGx, t_start, t_end), ...
        Time_MCR(t_MMGx, t_start, t_end), ...
        Time_AOC(t_MMGx, t_start, t_end), ...
        Time_skewness(t_MMGx, t_start, t_end), ...
        Time_kurtosis(t_MMGx, t_start, t_end), ...
        Time_mean_gradient(t_MMGx, t_start, t_end), ...
        Time_SNR(t_MMGx, t_start, t_end), ...
        Time_mean_xcorr(t_MMGx, t_start, t_end), ...
        Time_std_xcorr(t_MMGx, t_start, t_end), ...
        Time_sum_xcorr(t_MMGx, t_start, t_end), ...
        Freq_mean(t_MMGx, t_start, t_end), ...
        Freq_median(t_MMGx, t_start, t_end), ...
        Freq_max(t_MMGx, t_start, t_end), ...
        Freq_min(t_MMGx, t_start, t_end), ...
        Freq_std(t_MMGx, t_start, t_end), ...
        Freq_std_error(t_MMGx, t_start, t_end), ...
        Freq_var(t_MMGx, t_start, t_end), ...
        Freq_peakfreq(t_MMGx, t_start, t_end), ...
        Freq_avg_power(t_MMGx, t_start, t_end), ...
        Freq_totalpower(t_MMGx, t_start, t_end), ...
        Freq_skewness(t_MMGx, t_start, t_end), ...
        Freq_kurtosis(t_MMGx, t_start, t_end), ...
        Freq_mean_psd(t_MMGx, t_start, t_end), ...
        Freq_median_psd(t_MMGx, t_start, t_end), ...
        Freq_std_error_psd(t_MMGx, t_start, t_end), ...
        Time_mean(t_MMGy, t_start, t_end), ... 
        Time_median(t_MMGy, t_start, t_end), ... 
        Time_max(t_MMGy, t_start, t_end), ... 
        Time_min(t_MMGy, t_start, t_end), ... 
        Time_std_dev(t_MMGy, t_start, t_end), ... 
        Time_std_error(t_MMGy, t_start, t_end), ... 
        Time_var(t_MMGy, t_start, t_end), ... 
        Time_RMS(t_MMGy, t_start, t_end), ... 
        Time_meanAbsVal(t_MMGy, t_start, t_end), ... 
        Time_normalizedMean(t_MMGy, t_start, t_end), ... 
        Time_normalizedRMS(t_MMGy, t_start, t_end), ... 
        Time_normalizedStDev(t_MMGy, t_start, t_end), ... 
        Time_ssi(t_MMGy, t_start, t_end), ... 
        Time_ZCR(t_MMGy, t_start, t_end), ... 
        Time_MCR(t_MMGy, t_start, t_end), ... 
        Time_AOC(t_MMGy, t_start, t_end), ... 
        Time_skewness(t_MMGy, t_start, t_end), ... 
        Time_kurtosis(t_MMGy, t_start, t_end), ... 
        Time_mean_gradient(t_MMGy, t_start, t_end), ... 
        Time_SNR(t_MMGy, t_start, t_end), ... 
        Time_mean_xcorr(t_MMGy, t_start, t_end), ... 
        Time_std_xcorr(t_MMGy, t_start, t_end), ... 
        Time_sum_xcorr(t_MMGy, t_start, t_end), ... 
        Freq_mean(t_MMGy, t_start, t_end), ... 
        Freq_median(t_MMGy, t_start, t_end), ... 
        Freq_max(t_MMGy, t_start, t_end), ... 
        Freq_min(t_MMGy, t_start, t_end), ... 
        Freq_std(t_MMGy, t_start, t_end), ... 
        Freq_std_error(t_MMGy, t_start, t_end), ... 
        Freq_var(t_MMGy, t_start, t_end), ... 
        Freq_peakfreq(t_MMGy, t_start, t_end), ... 
        Freq_avg_power(t_MMGy, t_start, t_end), ... 
        Freq_totalpower(t_MMGy, t_start, t_end), ... 
        Freq_skewness(t_MMGy, t_start, t_end), ... 
        Freq_kurtosis(t_MMGy, t_start, t_end), ... 
        Freq_mean_psd(t_MMGy, t_start, t_end), ... 
        Freq_median_psd(t_MMGy, t_start, t_end), ... 
        Freq_std_error_psd(t_MMGy, t_start, t_end), ... 
        Time_mean(t_MMGz, t_start, t_end), ... 
        Time_median(t_MMGz, t_start, t_end), ... 
        Time_max(t_MMGz, t_start, t_end), ... 
        Time_min(t_MMGz, t_start, t_end), ... 
        Time_std_dev(t_MMGz, t_start, t_end), ... 
        Time_std_error(t_MMGz, t_start, t_end), ... 
        Time_var(t_MMGz, t_start, t_end), ... 
        Time_RMS(t_MMGz, t_start, t_end), ... 
        Time_meanAbsVal(t_MMGz, t_start, t_end), ... 
        Time_normalizedMean(t_MMGz, t_start, t_end), ... 
        Time_normalizedRMS(t_MMGz, t_start, t_end), ... 
        Time_normalizedStDev(t_MMGz, t_start, t_end), ... 
        Time_ssi(t_MMGz, t_start, t_end), ... 
        Time_ZCR(t_MMGz, t_start, t_end), ... 
        Time_MCR(t_MMGz, t_start, t_end), ... 
        Time_AOC(t_MMGz, t_start, t_end), ... 
        Time_skewness(t_MMGz, t_start, t_end), ... 
        Time_kurtosis(t_MMGz, t_start, t_end), ... 
        Time_mean_gradient(t_MMGz, t_start, t_end), ... 
        Time_SNR(t_MMGz, t_start, t_end), ... 
        Time_mean_xcorr(t_MMGz, t_start, t_end), ... 
        Time_std_xcorr(t_MMGz, t_start, t_end), ... 
        Time_sum_xcorr(t_MMGz, t_start, t_end), ... 
        Freq_mean(t_MMGz, t_start, t_end), ... 
        Freq_median(t_MMGz, t_start, t_end), ... 
        Freq_max(t_MMGz, t_start, t_end), ... 
        Freq_min(t_MMGz, t_start, t_end), ... 
        Freq_std(t_MMGz, t_start, t_end), ... 
        Freq_std_error(t_MMGz, t_start, t_end), ... 
        Freq_var(t_MMGz, t_start, t_end), ... 
        Freq_peakfreq(t_MMGz, t_start, t_end), ... 
        Freq_avg_power(t_MMGz, t_start, t_end), ... 
        Freq_totalpower(t_MMGz, t_start, t_end), ... 
        Freq_skewness(t_MMGz, t_start, t_end), ... 
        Freq_kurtosis(t_MMGz, t_start, t_end), ... 
        Freq_mean_psd(t_MMGz, t_start, t_end), ... 
        Freq_median_psd(t_MMGz, t_start, t_end), ... 
        Freq_std_error_psd(t_MMGz, t_start, t_end) 
        ];

    end
    features_table = array2table(features);
    features_table.Properties.VariableNames(1:num_feat) = {
        'EMG_i'...
        'EMG_t_start'...
        'EMG_t_end'...
        'EMG_Time_length'...
        'EMG_Time_mean'...
        'EMG_Time_median'...
        'EMG_Time_max'...
        'EMG_Time_min'...
        'EMG_Time_std_dev'...
        'EMG_Time_std_error'...
        'EMG_Time_var'...
        'EMG_Time_RMS'...
        'EMG_Time_meanAbsVal'...
        'EMG_Time_normalizedMean'...
        'EMG_Time_normalizedRMS'...
        'EMG_Time_normalizedStDev'...
        'EMG_Time_ssi'...
        'EMG_Time_ZCR'...
        'EMG_Time_MCR'...
        'EMG_Time_AOC'...
        'EMG_Time_skewness'...
        'EMG_Time_kurtosis'...
        'EMG_Time_mean_gradient'...
        'EMG_Time_SNR'...
        'EMG_Time_mean_xcorr'...
        'EMG_Time_std_xcorr'...
        'EMG_Time_sum_xcorr'...
        'EMG_Freq_mean'...
        'EMG_Freq_median'...
        'EMG_Freq_max'...
        'EMG_Freq_min'...
        'EMG_Freq_std'...
        'EMG_Freq_std_error'...
        'EMG_Freq_var'...
        'EMG_Freq_peakfreq'...
        'EMG_Freq_avg_power'...
        'EMG_Freq_totalpower'...
        'EMG_Freq_skewness'...
        'EMG_Freq_kurtosis'...
        'EMG_Freq_mean_psd'...
        'EMG_Freq_median_psd'...
        'EMG_Freq_std_error_psd'...
        'EMG;MMGx_corr'...
        'EMG;MMGy_corr'...
        'EMG;MMGz_corr'...
        'MMGx;MMGy_corr'...
        'MMGx;MMGz_corr'...
        'MMGy;MMGz_corr'...
        'MMGx_Time_mean'...
        'MMGx_Time_median'...
        'MMGx_Time_max'...
        'MMGx_Time_min'...
        'MMGx_Time_std_dev'...
        'MMGx_Time_std_error'...
        'MMGx_Time_var'...
        'MMGx_Time_RMS'...
        'MMGx_Time_meanAbsVal'...
        'MMGx_Time_normalizedMean'...
        'MMGx_Time_normalizedRMS'...
        'MMGx_Time_normalizedStDev'...
        'MMGx_Time_ssi'...
        'MMGx_Time_ZCR'...
        'MMGx_Time_MCR'...
        'MMGx_Time_AOC'...
        'MMGx_Time_skewness'...
        'MMGx_Time_kurtosis'...
        'MMGx_Time_mean_gradient'...
        'MMGx_Time_SNR'...
        'MMGx_Time_mean_xcorr'...
        'MMGx_Time_std_xcorr'...
        'MMGx_Time_sum_xcorr'...
        'MMGx_Freq_mean'...
        'MMGx_Freq_median'...
        'MMGx_Freq_max'...
        'MMGx_Freq_min'...
        'MMGx_Freq_std'...
        'MMGx_Freq_std_error'...
        'MMGx_Freq_var'...
        'MMGx_Freq_peakfreq'...
        'MMGx_Freq_avg_power'...
        'MMGx_Freq_totalpower'...
        'MMGx_Freq_skewness'...
        'MMGx_Freq_kurtosis'...
        'MMGx_Freq_mean_psd'...
        'MMGx_Freq_median_psd'...
        'MMGx_Freq_std_error_psd'...
        'MMGy_Time_mean'...
        'MMGy_Time_median'...
        'MMGy_Time_max'...
        'MMGy_Time_min'...
        'MMGy_Time_std_dev'...
        'MMGy_Time_std_error'...
        'MMGy_Time_var'...
        'MMGy_Time_RMS'...
        'MMGy_Time_meanAbsVal'...
        'MMGy_Time_normalizedMean'...
        'MMGy_Time_normalizedRMS'...
        'MMGy_Time_normalizedStDev'...
        'MMGy_Time_ssi'...
        'MMGy_Time_ZCR'...
        'MMGy_Time_MCR'...
        'MMGy_Time_AOC'...
        'MMGy_Time_skewness'...
        'MMGy_Time_kurtosis'...
        'MMGy_Time_mean_gradient'...
        'MMGy_Time_SNR'...
        'MMGy_Time_mean_xcorr'...
        'MMGy_Time_std_xcorr'...
        'MMGy_Time_sum_xcorr'...
        'MMGy_Freq_mean'...
        'MMGy_Freq_median'...
        'MMGy_Freq_max'...
        'MMGy_Freq_min'...
        'MMGy_Freq_std'...
        'MMGy_Freq_std_error'...
        'MMGy_Freq_var'...
        'MMGy_Freq_peakfreq'...
        'MMGy_Freq_avg_power'...
        'MMGy_Freq_totalpower'...
        'MMGy_Freq_skewness'...
        'MMGy_Freq_kurtosis'...
        'MMGy_Freq_mean_psd'...
        'MMGy_Freq_median_psd'...
        'MMGy_Freq_std_error_psd'...
        'MMGz_Time_mean'...
        'MMGz_Time_median'...
        'MMGz_Time_max'...
        'MMGz_Time_min'...
        'MMGz_Time_std_dev'...
        'MMGz_Time_std_error'...
        'MMGz_Time_var'...
        'MMGz_Time_RMS'...
        'MMGz_Time_meanAbsVal'...
        'MMGz_Time_normalizedMean'...
        'MMGz_Time_normalizedRMS'...
        'MMGz_Time_normalizedStDev'...
        'MMGz_Time_ssi'...
        'MMGz_Time_ZCR'...
        'MMGz_Time_MCR'...
        'MMGz_Time_AOC'...
        'MMGz_Time_skewness'...
        'MMGz_Time_kurtosis'...
        'MMGz_Time_mean_gradient'...
        'MMGz_Time_SNR'...
        'MMGz_Time_mean_xcorr'...
        'MMGz_Time_std_xcorr'...
        'MMGz_Time_sum_xcorr'...
        'MMGz_Freq_mean'...
        'MMGz_Freq_median'...
        'MMGz_Freq_max'...
        'MMGz_Freq_min'...
        'MMGz_Freq_std'...
        'MMGz_Freq_std_error'...
        'MMGz_Freq_var'...
        'MMGz_Freq_peakfreq'...
        'MMGz_Freq_avg_power'...
        'MMGz_Freq_totalpower'...
        'MMGz_Freq_skewness'...
        'MMGz_Freq_kurtosis'...
        'MMGz_Freq_mean_psd'...
        'MMGz_Freq_median_psd'...
        'MMGz_Freq_std_error_psd'...
        };
    output_table = features_table;
    output_array = features;
catch ME
    ME.message
    ME.identifier
    ME.cause
    disp(filename)
    for i = 1:numel(ME.stack)
        ME.stack(i)
    end
end


end